# Generated by Django 2.2.19 on 2021-09-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Название группы"),
                ),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(verbose_name="")),
            ],
        ),
    ]
